name: Lint

on:
  pull_request:
    paths:
     - "test_code/**.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run black on diffed files only 
        run: git diff --name-only $GITHUB_BASE_REF $GITHUB_HEAD_REF | grep "*.py" | xargs black --check --verbose