name: Lint

on:
  pull_request:
    paths:
     - "test_code/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run black on diffed files only
        run: |
          git diff --name-only "origin/$GITHUB_BASE_REF" "origin/$GITHUB_HEAD_REF" | grep -E "[_\/a-zA-Z0-9]*\.py$" | xargs black --check --verbose
