name: Lint

on:
  pull_request:
    paths:
     - "test_code/**.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run black on diffed files only
        #run: echo $GITHUB_BASE_REF
        #run: echo $GITHUB_HEAD_REF 
        run: git diff --name-only "origin/$GITHUB_BASE_REF" $GITHUB_HEAD_REF | grep "*.py" 
        #xargs black --check --verbose
